[package]
name = "kadou"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
inquire.workspace = true
kadou-core = { path = "../kadou-core", version = "0.1.0" }
kadou-exec = { path = "../kadou-exec", version = "0.1.0" }
kadou-mcp = { path = "../kadou-mcp", version = "0.1.0" }
rust-embed.workspace = true
similar.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
toml_edit.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[dev-dependencies]
assert_cmd.workspace = true
humantime.workspace = true
predicates.workspace = true
serde_json.workspace = true
tempfile.workspace = true
